# this file is used to build containers locally on develop host.

version: '2'

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    image: postgres:9.6
    expose:
      - "5432"

  broker:
    image: rabbitmq:latest
    #command:
      #- rabbitmq-server
    ports:
      - "5672:5672"

  app:
    environment:
      DJANGO_SECRET_KEY: changeme
      DATABASE_URL: postgres://app_user:changeme@db/app_db
    build:
      context: .
      dockerfile: dockerfiles/docker_app.conf
    volumes:
      - static-root:/code/bakerydemo/collect_static
      - media-root:/code/bakerydemo/media
    links:
      - db:db
    ports:
      - "8001:8001"
    depends_on:
      - db

  nginx:
    volumes:
      - media-root:/code/bakerydemo/media
      - static-root:/code/bakerydemo/static
    build:
     context: .
     dockerfile: dockerfiles/docker_nginx.conf
    depends_on:
     - app
    labels:
      #  Set your www.hostname.com as Host in production.
      #- "traefik.http.routers.my-app.rule=Host(`whoami.docker.localhost`)"
      - "traefik.http.routers.nginx.rule=Host(`127.0.0.1`, `localhost`)"

  traefik:
    image: "traefik:v2.0.1"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  media-root:
  static-root: